config/routes.rb
Rails.application.routes.draw do

  resources :campaigns do 
    resources :votes
  end

  root 'campaigns#index'

end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  has_many :votes
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :campaign
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController

  def index
    @campaigns = Campaign.all
  end

  def show
     @campaign = Campaign.find params[:id]
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def index
    @votes = Vote.all
    if params[:campaign_id]
      @campaignvotes = @votes.where(:campaign => params[:campaign_id], :validity => "during")
      @failedvotes = @votes.where(:campaign => params[:campaign_id], :validity => ["pre", "post"])
      candidates = find_candidates(@campaignvotes)
      @candidate_array = []
      candidates.each do |candidate|
        candidate = @campaignvotes.where(choice: candidate)
        @candidate_array << candidate
      end
    end
  end

  def find_candidates(votes)
    candidates = []
    votes.each {|vote| candidates << vote.choice}
    candidates.uniq
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/campaigns/_campaign.html.erb
 <div class="row">
    <h1><%= link_to campaign.name, campaign_votes_path(campaign) %></h1>
  </div>

app/views/campaigns/index.html.erb
<div class='row'>
<h1> CAMPAIGNS: </h1>
<%= render @campaigns %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VoteSystem</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/votes/index.html.erb
<h1><%= link_to 'HOME', campaigns_path %> </h1>
<div class='row'>
<h1>SUCCESSFUL VOTES = <%= @campaignvotes.count %></h1>
<h1>FAILED VOTES = <%= @failedvotes.count %></h1>
<h2>TOTAL CANDIDATES = <%= @candidate_array.count %></h2>
<%= @candidate_array.each do |candidate|%>
<h3> <%= candidate[0].choice %>: <%= candidate.count %></h3>
    <% end %>
</div>